src/TRestDetectorSingleChannelAnalysisProcess.cxx

Related to
https://github.com/rest-for-physics/framework/pull/27
this is another showstopper for the latest ROOT release / C++14.
On this version it complains without it:
```
/home/basti/src/rest_framework/source/libraries/detector/src/TRestDetectorSingleChannelAnalysisProcess.cxx: In member function 'void TRestDetectorSingleChann
elAnalysisProcess::PrintChannelSpectrums(std::string)':
/home/basti/src/rest_framework/source/libraries/detector/src/TRestDetectorSingleChannelAnalysisProcess.cxx:274:11: error: variable 'TLine pLine' has initiali
zer but incomplete type
274 |     TLine pLine = TLine();
|           ^~~~~
/home/basti/src/rest_framework/source/libraries/detector/src/TRestDetectorSingleChannelAnalysisProcess.cxx:274:25: error: invalid use of incomplete type 'cla
ss TLine'
274 | …
```

include `TLine.h` to compile with C++14 / ROOT v6.24

---

src/TRestDetectorReadoutPlane.cxx

It was a very old bug maybe due to typo error. The code of `TRestReadoutPlane::GetX()` and `TRestReadoutPlane::GetY()` was not symmetric previously for on-90 deg rotation.

TRestReadout handles correctly for non-90 deg rotation

---

macros/REST_Detector_CheckReadout.C

- Added few lines to document the CheckReadout macro.
It will be shown when executing
```
restManager ListMacros
```
- Added an offset so that we will be able to shift the 128-bits mask to select channels of higher value.

REST_Detector_CheckReadout updates

---

CMakeLists.txt
inc/TRestDetectorHitsToSignalProcess.h
src/TRestDetectorHitsToSignalProcess.cxx

This updates `TRestDetectorHitsToSignalProcess` in order to use the standard/common configuration parameters in REST.
The change is important because that way we will be able to use for example, statements as `[TRestDetector::fPressure]` at the process parameter definitions.
It also fixes version 1.3 of this library.

Detector signal updates

---

inc/TRestDetectorTriggerAnalysisProcess.h
src/TRestDetectorTriggerAnalysisProcess.cxx

This PR just removes unncessary `TRestDetectorGas` and `TRestDetectorReadout` dependencies at this pure analysis process.
It has also been documented using official documentation patterns.

Trigger analysis fixes

---

inc/TRestDetectorSingleChannelAnalysisProcess.h
src/TRestDetectorSingleChannelAnalysisProcess.cxx

Fixing compilation due to new protections of `TRestDetectorReadout` added in the parallel framework branch.
`TRestDetectorSingleChannelAnalysisProcess::SaveGainMetadata` has been also commented since I believe does not follow the common way to save metadata output data.

TRestDetectorSingleChannelAnalysisProcess fixes

---

src/TRestDetectorHitsEvent.cxx
src/TRestDetectorReadoutModule.cxx
src/TRestDetectorReadoutPixel.cxx

This PR is connected to rest-for-physics/framework#122
- Updated TRestReadoutPixel default tolerance.
- Updated default drawing pitch to 0.5mm

Alphas example

---

CMakeLists.txt

Using recommended Garfield CMake commands to link it.
On different systems the `lib` folder may be named differently (`lib64`). This is a problem in NAF-IAXO.

Fix installation issue due to Garfield

---

inc/TRestDetectorHitsEvent.h
inc/TRestDetectorSignalEvent.h
src/TRestDetectorHitsEvent.cxx
src/TRestDetectorSignalEvent.cxx

After new changes in the code, it seems that `DrawEvent` is not working for some inherited classes from `TRestEvent`
This PR fix this bug by replacing:
```
- TPad* DrawEvent(TString option = "");
+ TPad* DrawEvent(const TString& option = "");
```

Fixing bug on inheritance of DrawEvent from base class

---

src/TRestDetectorHitsEvent.cxx
src/TRestDetectorReadoutModule.cxx

Related to https://github.com/rest-for-physics/framework/pull/231. Array initialization with dynamic length is not available for msvc. Changed to vector. e.g. `Double_t x[nHits];` --> `vector<Double_t> x(nHits);`

replaced dynamic length array initializaion

---

.github/workflows/validation.yml

Added github pipeline to detectorlib:
- Replicates gitlab pipeline, although only stand alone build of detectorlib is performed
- Check against framework pipeline
- Contributes to https://github.com/rest-for-physics/framework/issues/45

Adding github detectorlib pipeline

---

macros/REST_Detector_HitCentering.C

A third histogram for Z-events is now also produced.

REST_Detector_HitCentering.C now also works for Z-hits

---

inc/TRestDetectorHitsEvent.h
inc/TRestDetectorSignal.h
inc/TRestDetectorSignalEvent.h
src/TRestDetectorHitsEvent.cxx

This PR is required due to a member name change in `TRestHits`, which was public. Now members have been made protected in order to prevent these kind of side effects.
* https://github.com/rest-for-physics/framework/pull/263

Update required from framework/TRestHits

---

src/TRestDetectorGas.cxx

Units of the Y-axis of the longitudinal and transversal diffusion plots were wrong. It is now expressed in mm/sqrt(cm).

TRestDetectorGas: fixing the axis units in diffusion plots

---

inc/TRestDetectorSignal.h
inc/TRestDetectorSignalToHitsProcess.h
src/TRestDetectorSignal.cxx
src/TRestDetectorSignalToHitsProcess.cxx

This PR is to implement a new signalto hits method. It performs a gaussian fit to each signal in a signal event, and uses the parameters of this fit in `TRestDetectorSignalToHitsProcess`.
WORK IN PROGRESS
It currently has a bug because the signals in a signal event do not all start in the same time bin. See figure 1, where the black signal starts much earlier than the others.
Figure 1: sample signal event.
So when a histogram is filled with the points of each signal, each of them has a different starting position because some have this tail to the left (fig. 2), and some don't (fig. 3) which affects the gaussian fit parameters.
Figure 2: histogram used to fit the signal. In this case, there is a tail to the left.
Figure 3:  histogram used to fit the signal. In this case, there is no tail …

Gaus fit signal to hits

---

src/TRestDetectorSingleChannelAnalysisProcess.cxx

Related to https://github.com/rest-for-physics/detectorlib/issues/47 and https://github.com/rest-for-physics/framework/pull/290
No more hard-coded process names. We directly use pure observable names.

Avoid invoking hardcoded process names

---

CMakeLists.txt

Please, approve the new version to generate a detectorlib release.
I increased from 1.6 to 1.8 because the tag 1.7 already existed.

Increasing version to 1.8

---

src/TRestDetectorSignalRecoveryProcess.cxx

Update of TRestDetectorSignalRecoveryProcess

TRestDetectorSignalRecoveryProcess update

---

src/TRestDetectorSignalRecoveryProcess.cxx

Addressing segfault in TRestDetectorSignalRecoveryProcess
- Somehow this line `Int_t nPoints = fOutputSignalEvent->GetSignal(0)->GetNumberOfPoints();` is problematic and was causing the segmentation fault.
- Avoid use of `new`/`delete` in `recoveredSignal`
- Other minor changes in the code

Addressing segfault in TRestDetectorSignalRecoveryProcess

---

.github/workflows/validation.yml

The pipeline is failing because it does not find detectorlib installation.
See for example: https://github.com/rest-for-physics/axionlib/actions/runs/5175275109/jobs/9322828807?pr=69
The change in detectorlib validation pipeline does not take place till this PR will be merged. So we need to merge to do the test.
I implemented it inspired on the implementation of pipeline at rawlib

Adding cache detectorlib installation

---

inc/TRestDetectorHitsRotateAndTranslateProcess.h
src/TRestDetectorHitsRotateAndTranslateProcess.cxx

Update hits rotation inside detectorlib:
- Alternative (more clean IMHO) way to set parameters in the rml. Old syntax still works:
```
<addProcess type="TRestDetectorHitsRotateAndTranslateProcess">
<parameter name="rotationCenter" value="(0,0,0)mm" />
<parameter name="translation" value="(0,10,0)mm" />
<parameter name="rotationZ" value="45deg" />
</addProcess>
```
- New parameter "rotationCenter" to specify the rotation center (defaults to (0,0,0)). **Before the hits were rotation around the mean position of the hits, which does not make much sense to me as a default behaviour and this was not modifiable by the user. I was not aware of this until I looked at the code, perhaps others such as @cmargalejo are also unaware (because you mentioned to rotate the hits for the 45º rotated readout …

Update hits rotation

---

macros/REST_Detector_CheckReadout.C
macros/REST_Detector_ViewReadout.C
src/TRestDetectorDaqChannelSwitchingProcess.cxx
src/TRestDetectorGarfieldDriftProcess.cxx
src/TRestDetectorGas.cxx
src/TRestDetectorHits3DReconstructionProcess.cxx
src/TRestDetectorReadoutEventViewer.cxx
src/TRestDetectorReadoutPlane.cxx
src/TRestDetectorSignalEvent.cxx
src/TRestDetectorSingleChannelAnalysisProcess.cxx

Remove explicit numeric limits

---

src/TRestDetectorHitsToSignalProcess.cxx

Some large times in the geant4 simulation were being converted into negative due to overflow.

Fix negative time due to overflow

---

inc/TRestDetectorSignal.h
src/TRestDetectorHitsToSignalProcess.cxx
src/TRestDetectorSignal.cxx
src/TRestDetectorSignalEvent.cxx

Use double instead of float, since sometimes this can cause problem for very large times (coming from geant4).

TRestRawSignal - Use double for storage instead of float

---

inc/TRestDetectorGarfieldDriftProcess.h
inc/TRestDetectorHitsToSignalProcess.h
inc/TRestDetectorSignalToHitsProcess.h
src/TRestDetectorElectronDiffusionProcess.cxx
src/TRestDetectorGarfieldDriftProcess.cxx
src/TRestDetectorHitsToSignalProcess.cxx
src/TRestDetectorSignalToHitsProcess.cxx

Because gas pressure is defined to be 1.0 by default, the condition where it checks if it's undefined then load it from the gas metadata is never triggered. This change will make it that if undefined, it will attempt to load it from the gas metadata.

Correctly initialize gas pressure

---

inc/TRestDetectorHitsSmearingProcess.h
src/TRestDetectorHitsSmearingProcess.cxx

Smearing process allow channel type selection

---

inc/TRestDetectorElectronDiffusionProcess.h
src/TRestDetectorElectronDiffusionProcess.cxx

Revising `TRestDetectorElectronDiffusionProcess` to take into account the gas Fano factor in the number of electrons  created (work in progress)

TRestDetectorElectronDiffusionProcess taking into account the fano factor

---

inc/TRestDetectorHitsReadoutAnalysisProcess.h
src/TRestDetectorHitsReadoutAnalysisProcess.cxx

@mariajmz  and @JPorron found an error when using this process with experimental data. This is because experimental data has only relative z so it cannot be used to check if a hit is inside readout or not.
This PR introduces a new parameter `ignoreZ` which when set to `true` will ignore z when retrieving channel from position. It is disabled by default so the behaviour remains unchanged unless this option is set.

Add option to ignore z in `TRestDetectorHitsReadoutAnalysisProcess`

---

inc/TRestDetectorSignal.h
src/TRestDetectorSignal.cxx

DON'T MERGE: This is a work in progress
@JPorron and me detected a problem with the fitting methods: the limits for the fits are hardcoded and are only valid for a sampling time of 20 ns.

Fixing problems with TRestDetectorSignal fitting methods

---

inc/TRestDetectorSignal.h
src/TRestDetectorSignal.cxx
src/TRestDetectorSignalToHitsProcess.cxx

New we skip the peak if it's not being found, instead of returning energy -1

Use `std::optional` for peak fitting (which can fail) and other minor refactorings
