inc/TRestDetector.h, src/TRestDetector.cxx
This pull-request is connected with the following one.
https://github.com/rest-for-physics/framework/pull/35
- Documentation updated
- PrintMetadata simplified output
- UpdateMetadataMembers implemented to calculate the sampling time.
=> TRestDetector updates

.gitlab-ci.yml
=> .gitlab-ci.yml Fixing pipeline

pipeline/validateLibrary.py
=> validateLibrary.py fixing encoding

CMakeLists.txt
=> CMakeLists.txt increasing library version to 1.2

inc/TRestDetectorDriftVolume.h, src/TRestDetectorGas.cxx
It fixes problems reported at forum post:
http://rest-forum.unizar.es/t/finding-the-correct-value-of-drift-velocity/507
=> Gas plot fix

inc/TRestDetectorTriggerAnalysisProcess.h, src/TRestDetectorHits3DReconstructionProcess.cxx
It fixes a problem introduced at PR #17
=> Trigger analysis fixes

CMakeLists.txt
Summary of changes available at https://github.com/rest-for-physics/detectorlib/releases/tag/v1.4.
=> Fixing release 1.4

.gitlab-ci.yml
=> .gitlab-ci.yml fixed pipeline to use new CMAKE_INSTALL_PREFIX

macros/REST_Detector_CheckReadout.C
=> REST_Detector_CheckReadout added more output

inc/TRestDetectorSignalToHitsProcess.h, src/TRestDetectorSignalToHitsProcess.cxx
=> Documenting

CMakeLists.txt, inc/TRestDetectorReadoutPixel.h, src/TRestDetectorReadout.cxx, src/TRestDetectorReadoutPixel.cxx
- Fixed pipeline by using custom defined pixelTolerance
=> Alphas example

inc/TRestDetectorDaqChannelSwitchingProcess.h, inc/TRestDetectorDriftVolume.h, inc/TRestDetectorGas.h, inc/TRestDetectorHitsAnalysisProcess.h, inc/TRestDetectorPositionMappingProcess.h, inc/TRestDetectorSingleChannelAnalysisProcess.h, macros/REST_Detector_ViewHitsEvent.C, src/TRestDetectorElectronDiffusionProcess.cxx, src/TRestDetectorGarfieldDriftProcess.cxx, src/TRestDetectorGas.cxx, src/TRestDetectorHits3DReconstructionProcess.cxx, src/TRestDetectorHitsToSignalProcess.cxx, src/TRestDetectorPositionMappingProcess.cxx, src/TRestDetectorReadout.cxx, src/TRestDetectorReadoutChannel.cxx, src/TRestDetectorReadoutModule.cxx, src/TRestDetectorReadoutPixel.cxx, src/TRestDetectorReadoutPlane.cxx, src/TRestDetectorSignalChannelActivityProcess.cxx, src/TRestDetectorSignalViewerProcess.cxx, src/TRestDetectorSingleChannelAnalysisProcess.cxx, test/files/TRestDetectorElectronDiffusionProcess.rml, test/files/TRestDetectorGasExample.rml
=> Jgalan recover gasfix

CMakeLists.txt
Just for tagging the latest detectorlib to be included in v2.3.13
=> Updating CMakeLists.txt to 1.9

src/TRestDetectorAvalancheProcess.cxx, src/TRestDetectorGarfieldDriftProcess.cxx, src/TRestDetectorGas.cxx, src/TRestDetectorHits3DReconstructionProcess.cxx, src/TRestDetectorHitsAnalysisProcess.cxx, src/TRestDetectorHitsEvent.cxx, src/TRestDetectorHitsEventViewer.cxx, src/TRestDetectorHitsGaussAnalysisProcess.cxx, src/TRestDetectorHitsNormalizationProcess.cxx, src/TRestDetectorHitsReductionProcess.cxx, src/TRestDetectorHitsRotateAndTranslateProcess.cxx, src/TRestDetectorHitsSmearingProcess.cxx, src/TRestDetectorHitsToSignalProcess.cxx, src/TRestDetectorPositionMappingProcess.cxx, src/TRestDetectorReadout.cxx, src/TRestDetectorReadoutPlane.cxx, src/TRestDetectorSignal.cxx, src/TRestDetectorSignalToHitsProcess.cxx, src/TRestDetectorSingleChannelAnalysisProcess.cxx, test/src/Processes.cxx
=> Solving numerous compilation warnings

src/TRestDetectorReadoutModule.cxx
This will fix an issue with MacOs system compilation. The change has only effect on MacOs systems.
=> TRestDetectorReadoutModule. Just adding unistd header for MacOs installations

inc/TRestDetectorHitmapAnalysisProcess.h, inc/TRestDetectorHitsRotationProcess.h, inc/TRestDetectorHitsSpecularProcess.h, inc/TRestDetectorHitsTranslationProcess.h
Compilation issue appears after PR https://github.com/rest-for-physics/detectorlib/pull/100
It seems that the issue appears after merging https://github.com/rest-for-physics/detectorlib/pull/97
This PR solves the compilation issue
=> Addressing compilation issue after merge with master

inc/TRestDetectorHitsEvent.h, src/TRestDetectorElectronDiffusionProcess.cxx, src/TRestDetectorFiducializationProcess.cxx, src/TRestDetectorGarfieldDriftProcess.cxx, src/TRestDetectorHits3DReconstructionProcess.cxx, src/TRestDetectorHitsAnalysisProcess.cxx, src/TRestDetectorHitsEvent.cxx, src/TRestDetectorHitsNormalizationProcess.cxx, src/TRestDetectorPositionMappingProcess.cxx, src/TRestDetectorSignalToHitsProcess.cxx
=> Fix pipeline

src/TRestDetectorGas.cxx
- https://github.com/rest-for-physics/framework/pull/511
=> Add option to PID prefix on downloads to avoid faults

src/TRestDetectorHitsEvent.cxx
The following PR should fix compilation issues under MacOs.
=> TRestDetectorHitsEvent::Sort disabled for MacOs

inc/TRestDetectorGas.h, src/TRestDetectorGas.cxx
Adding a new method to retrieve the Fano factor from Garfield::MediumMagboltz
=> Get Fano factor from Garfield

src/TRestDetectorHitsReadoutAnalysisProcess.cxx
=> Readout Analysis: small fix
